services:
  _defaults:
    autowire: true
    autoconfigure: true

  messenger.transport.kafka.factory:
    class: FRZB\Component\Messenger\Bridge\Kafka\Transport\KafkaTransportFactory
    tags:
      - { name: 'messenger.transport_factory' }
