parameters:
  env(MESSENGER_KAFKA_DEBUG): false
  frzb.messenger.kafka.debug: '%env(bool:MESSENGER_KAFKA_DEBUG)'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  FRZB\Component\Messenger\Bridge\Kafka\Transport\KafkaLogger: ~

  messenger.transport.kafka.factory:
    class: FRZB\Component\Messenger\Bridge\Kafka\Transport\KafkaTransportFactory
    arguments:
      - '@FRZB\Component\Messenger\Bridge\Kafka\Transport\KafkaLogger'
      - '%frzb.messenger.kafka.debug%'
    tags:
      - { name: 'messenger.transport_factory' }
