build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit --colors=always --verbose --configuration phpunit.xml.dist --log-junit var/tests/.phpunit.output.xml --coverage-clover var/tests/coverage/coverage.xml
            coverage:
              file: var/tests/coverage/coverage.xml
              format: clover

  dependencies:
    before:
      - sudo apt-get install -y librdkafka1 librdkafka-dev

  environment:
    php:
      version: 8.0.13
      pecl_extensions:
        - rdkafka
        - xdebug
filter:
  excluded_paths:
    - "Tests/*"
    - "var/*"
    - "Resources/*"
  dependency_paths:
    - "vendor/*"
